version: "3.9"

services:

  app:
    container_name: crashmap-app
    hostname: ${APP_HOST_DOCKER?-}
    build:
      context: .
      dockerfile: app.Dockerfile
      args:
        - BUILD_ENVIRONMENT=staging
        - DOCKER_NODE_TAG=${DOCKER_NODE_TAG?-}
        - DOCKER_PYTHON_TAG=${DOCKER_PYTHON_TAG?-}
        - APP_PORT_DOCKER=${APP_PORT_DOCKER?-}
        - DATABASE_SCHEME=${DATABASE_SCHEME?-}
        - DATABASE_HOST=${DATABASE_HOST?-}
        - DATABASE_PORT=${DATABASE_PORT?-}
        - DATABASE_NAME=${DATABASE_NAME?-}
        - DATABASE_USERNAME=${DATABASE_USERNAME?-}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD?-}
    ports:
      - "${APP_PORT?-}:${APP_PORT_DOCKER?-}"
    depends_on:
      - database

  database:
    container_name: crashmap-database
    hostname: ${DATABASE_HOST_DOCKER?-}
    build:
      context: .
      dockerfile: database.Dockerfile
      args:
        - DOCKER_POSTGIS_TAG=${DOCKER_POSTGIS_TAG?-}
        - DATABASE_PORT_DOCKER=${DATABASE_PORT_DOCKER?-}
        - DATABASE_USERNAME=${DATABASE_USERNAME?-}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD?-}
        - DATABASE_NAME=${DATABASE_NAME?-}
    ports:
      - "${DATABASE_PORT?-}:${DATABASE_PORT_DOCKER?-}"

  pgadmin:
    container_name: crashmap-pgadmin
    build:
      context: .
      dockerfile: pgadmin.Dockerfile
      args:
        - DOCKER_PGADMIN_TAG=${DOCKER_PGADMIN_TAG?-}
        - PGADMIN_USERNAME=${PGADMIN_USERNAME?-}
        - PGADMIN_PASSWORD=${PGADMIN_PASSWORD?-}
        - DATABASE_HOST_DOCKER=${DATABASE_HOST_DOCKER?-}
        - DATABASE_PORT_DOCKER=${DATABASE_PORT_DOCKER?-}
        - DATABASE_NAME=${DATABASE_NAME?-}
        - DATABASE_USERNAME=${DATABASE_USERNAME?-}
    ports:
      - "${PGADMIN_PORT?-}:80"
    depends_on:
      - database
