version: "3.9"

services:

  database:
    container_name: crashmap-database
    hostname: ${DATABASE_HOST_DOCKER?-}
    build:
      context: .
      dockerfile: database.Dockerfile
      args:
        - DOCKER_POSTGIS_TAG=${DOCKER_POSTGIS_TAG?-}
        - DATABASE_PORT=${DATABASE_PORT?-}
        - DATABASE_PORT_DOCKER=${DATABASE_PORT_DOCKER?-}
        - DATABASE_USERNAME=${DATABASE_USERNAME?-}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD?-}
        - DATABASE_NAME=${DATABASE_NAME?-}
    ports:
      - "${DATABASE_PORT?-}:${DATABASE_PORT_DOCKER?-}"

  pgadmin:
    container_name: crashmap-pgadmin
    build:
      context: .
      dockerfile: pgadmin.Dockerfile
      args:
        - DOCKER_PGADMIN_TAG=${DOCKER_PGADMIN_TAG?-}
        - PGADMIN_USERNAME=${PGADMIN_USERNAME?-}
        - PGADMIN_PASSWORD=${PGADMIN_PASSWORD?-}
        - DATABASE_HOST_DOCKER=${DATABASE_HOST_DOCKER?-}
        - DATABASE_PORT_DOCKER=${DATABASE_PORT_DOCKER?-}
        - DATABASE_NAME=${DATABASE_NAME?-}
        - DATABASE_USERNAME=${DATABASE_USERNAME?-}
    ports:
      - "${PGADMIN_PORT?-}:80"
    depends_on:
      - database
